name: End-to-end tests
on:
  push:

  schedule:
    - cron: '0 15 * * *'  # trigger every day at T. uses UTC time (-4 from Toronto)

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

        
